### ISSUE TITLE
[FEAT] JWT 재발급 API 연결, 회원 탈퇴 API 연결

### ISSUE THREAD

**Issue by sjk4618** [Team-Going/Going-iOS#101]
## 🛠 Issue

- JWT 재발급 API 연결
- 회원 탈퇴 API 연결
- 프로필 조회 api(영서뷰에서 호출)
## 📝 To-do

- [x] JWT 재발급 API 연결
- [x] 회원 탈퇴 API 연결
- [x] 프로필 조회 api(영서뷰에서 호출)
