### ISSUE TITLE
[FEAT] 투두 생성 & 삭제 & 상세 조회 서버 통신

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#104]
## 🛠 Issue
투두 생성 & 삭제 & 상세 조회 서버 통신

## 📝 To-do

- [ ] 투두 생성 서버 통신
- [ ] 삭제 서버 통신
- [ ] 상세 조회 서버 통신
