### ISSUE TITLE
[FIX] 추가 수정사항

### ISSUE THREAD

**Issue by sjk4618** [Team-Going/Going-iOS#135]
## 🛠 Issue

- 엠티뷰 이미지 변경
- 전체 뷰컨 토스트메세지 확인
- x버튼 제거
## 📝 To-do

- [x] 엠티뷰 이미지 변경
- [ ]  전체 뷰컨 토스트메세지 확인
- [ ] x버튼 제거  
- [x] 투두 생성할 때, 담당자 비어있으면 저장하기버튼 비활성화
