### ISSUE TITLE
[REFACTOR] 에셋 사용법 변경

### ISSUE THREAD

**Issue by sjk4618** [Team-Going/Going-iOS#192]
## 🛠 Issue

- asset에 colorSet 만들어서 color 추가해두기
- 프로퍼티 줄바꿈 통일
- 에셋( 이미지, 컬러) resource 생성자 사용
## 📝 To-do

- [x] asset에 colorSet 만들어서 color 추가해두기 
- [x] 프로퍼티 줄바꿈 통일
- [x] 에셋( 이미지, 컬러) resource 생성자 사용
