### ISSUE TITLE
[FEAT] 아워투두 관련 새로운 수정사항 반영

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#214]
## 🛠 Issue
아워투두 관련 새로운 수정사항 반영

## 📝 To-do
- [x] ‘우리의 여행 취향 보러가기’ btn 추가 및 연결
- [x] 여행 친구 6명인 경우 ,'+' 버튼 클릭 시 토스트 띄우기
- [x] 그 외 변경된 UI 수정
