### ISSUE TITLE
[FEAT] 여행 TODO 수정 서버 통신

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#216]
## 🛠 Issue
여행 TODO 수정 서버 통신

## 📝 To-do
- [x] 여행 TODO 수정 서버 통신
- [x] 담당자 없는 케이스 로직 수정
- [x] 텍스트필드 & 텍스트뷰 clear button 추가
