### ISSUE TITLE
[FEAT] 내 프로필 & 친구 프로필 조회 서버 통신

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#220]
## 🛠 Issue
내 프로필 & 친구 프로필 조회 서버 통신

## 📝 To-do
- [x] 내 프로필 조회 서버 통신
- [x] 친구 프로필 조회 서버 통신
- [x] 엠티뷰 및 엠티 프로필 이미지 세팅
- [x] 아워투두 '취향 보러가기' 이미지 버튼 수정
