### ISSUE TITLE
[FEAT] 우리의 여행취향뷰와 여행프로필뷰 연결 및 내 여행프로필 취향태그뷰 수정

### ISSUE THREAD

**Issue by sjk4618** [Team-Going/Going-iOS#235]
## 🛠 Issue

- 우리의 여행취향뷰와 여행프로필뷰 연결
- 내여행프로필 취향테스트 다시하기 버튼 위치 수정
- 내여행프로필 취향테스트 다시했을 때 오류 수정
## 📝 To-do

- [x] 우리의 여행취향뷰와 여행프로필뷰 연결
- [x] 내여행프로필 취향테스트 다시하기 버튼 위치 수정
- [x] 내여행프로필 취향테스트 다시했을 때 오류 수정
