### ISSUE TITLE
[FEAT] 1차 QA 반영

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#247]
## 🛠 Issue
1차 QA 반영

## 📝 To-do
- [x] '할일 조회' 메모 스크롤 가능하도록 수정
- [x] '할일 수정' 에러 메세지 폰트 확인
- [x] '함께하는 친구들' 마지막 친구 터치 영역 수정
- [x] '나의 할 일' 두립이 레이아웃 수정
- [x] '~해요' 라이팅 수정
