### ISSUE TITLE
[FEAT] 1차 QA 대응

### ISSUE THREAD

**Issue by sjk4618** [Team-Going/Going-iOS#250]
## 🛠 Issue

- 성향테스트 안하고, 로그아웃하고 다시 로그인했을 때 에러
- 프로필 수정할 때, 변경사항 생겼을 때 수정버튼 활성화 시키기
- 성향테스트검사에서 클릭된 문항 볼드체로 변경하기
- 할일 할당자 버튼이미지 사용변경
## 📝 To-do

- [x] 성향테스트 안하고, 로그아웃하고 다시 로그인했을 때 에러
- [x] 프로필 수정할 때, 변경사항 생겼을 때 수정버튼 활성화 시키기
- [x] 성향테스트검사에서 클릭된 문항 볼드체로 변경하기
- [x] - 할일 할당자 버튼이미지 사용변경
