### ISSUE TITLE
[FEAT] 1차 추가 QA 대응

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#251]
## 🛠 Issue
1차 추가 QA 대응

## 📝 To-do

- [x] 투두 조회 시 닉네임이 이모티콘 3글자일 때 … 표시 수정
- [x] 여행 상세 조회에서 닉네임이 이모티콘 3글자일 때 투두 조회 시 2글자만 보이는 것 수정
- [x] 할일 조회 텍스트박스 하단(글자수, 메모)에 글자수 노출 안되도록 수정
- [x] 상대가 검사하지 않았을 때 ‘검사하러가기’cta 존재 & 활성화 현상 수정
