### ISSUE TITLE
[FEAT] 2차 QA

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#259]
## 🛠 Issue
 2차 QA

## 📝 To-do

- [x] 아워투두 프로필 찌부
- [x] 특수문자만 사용해서 닉네임 설정 시 우리여행에서 이름 태그가 길게 노출
- [x] 이모티콘 포함 닉네임 이름태그 양측 공백 폭이 다름
- [x] 할일추가 “할일을 입력해주세요” 글씨 색이 다름
- [x] “혼자할일” 글씨 박스 안에서 정렬
- [x] “나만 볼 수 있는 할일이에요” 혼자할일 태그와 거리 조절
- [x] 할일 수정에서 메모 글자수 활성화 시 색과 할일명 글자수 활성화 시 색이 다름
