### ISSUE TITLE
[FEAT] 성향테스트결과뷰 수정, 프로필 생성뷰 수정 

### ISSUE THREAD

**Issue by sjk4618** [Team-Going/Going-iOS#35]
## 🛠 Issue

- 성향테스트결과뷰 수정
- 프로필 생성뷰 수정
## 📝 To-do

- [x] 성향테스트결과뷰 수정
- [x] 프로필 생성뷰 수정
- [x] 프로필 생성뷰 키보드위로 버튼 올리기
- [x] 성향테스트결과뷰 이미지 저장 기능추가
